"""user_total_liabilities

Revision ID: 75d9e8b70de9
Revises: a83ea32b6c3f
Create Date: 2024-12-25 17:17:59.269774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d9e8b70de9'
down_revision: Union[str, None] = 'a83ea32b6c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('total_liabilities', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_liabilities')
    # ### end Alembic commands ###
