"""liability_template_normal_form

Revision ID: 1c4e8c51d04e
Revises: 655ad4c32887
Create Date: 2025-06-22 16:18:31.790398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4e8c51d04e'
down_revision: Union[str, None] = '655ad4c32887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liability_template', sa.Column('normal_form', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liability_template', 'normal_form')
    # ### end Alembic commands ###
