"""change_standard

Revision ID: c7ab5d7d8c8f
Revises: aa3051a06890
Create Date: 2025-04-26 16:06:01.784010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ab5d7d8c8f'
down_revision: Union[str, None] = 'aa3051a06890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard', sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False))
    op.alter_column('standard', 'count',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('standard', 'count',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('standard', 'is_deleted')
    # ### end Alembic commands ###
