"""liability_template_is_deleted

Revision ID: 691999e5df0e
Revises: 412c26b2a9c5
Create Date: 2025-05-10 01:53:31.147021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691999e5df0e'
down_revision: Union[str, None] = '412c26b2a9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liability_template', sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liability_template', 'is_deleted')
    # ### end Alembic commands ###
