"""credit_completed

Revision ID: b75ada202a8b
Revises: 54548053e5cc
Create Date: 2025-05-11 02:15:42.365018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75ada202a8b'
down_revision: Union[str, None] = '54548053e5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('credit', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit', 'completed')
    op.drop_column('credit', 'completed_at')
    # ### end Alembic commands ###
