"""liability_template__rm_unique_name

Revision ID: 54548053e5cc
Revises: 691999e5df0e
Create Date: 2025-05-11 01:50:41.170012

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '54548053e5cc'
down_revision: Union[str, None] = '691999e5df0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('liability_template_name_key', 'liability_template', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('liability_template_name_key', 'liability_template', ['name'])
    # ### end Alembic commands ###
