"""bot

Revision ID: 655ad4c32887
Revises: 50f7fa8876d6
Create Date: 2025-06-22 14:30:05.531521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655ad4c32887'
down_revision: Union[str, None] = '50f7fa8876d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authlink',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expire_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authlink_expire_datetime'), 'authlink', ['expire_datetime'], unique=False)
    op.add_column('user', sa.Column('telegram_chat_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_telegram_chat_id'), 'user', ['telegram_chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_chat_id'), table_name='user')
    op.drop_column('user', 'telegram_chat_id')
    op.drop_index(op.f('ix_authlink_expire_datetime'), table_name='authlink')
    op.drop_table('authlink')
    # ### end Alembic commands ###
