"""change_count_and_users

Revision ID: 29b6e9de8f6e
Revises: 31e432d307ab
Create Date: 2025-11-27 01:17:01.794910

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b6e9de8f6e'
down_revision: Union[str, None] = '31e432d307ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('completed_standard', 'count',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('credit', 'count',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('credit', 'completed_count',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('liability', 'count',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('liability_template', 'count',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('standard', 'count',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.add_column('user', sa.Column('weight', sa.Float(), server_default='70', nullable=False))
    op.add_column('user', sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), server_default='male', nullable=False))
    op.add_column('user', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.alter_column('user', 'total_liabilities',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'total_liabilities',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'sex')
    op.drop_column('user', 'weight')
    op.alter_column('standard', 'count',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('liability_template', 'count',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('liability', 'count',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('credit', 'completed_count',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('credit', 'count',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('completed_standard', 'count',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
