"""standards_normal_form

Revision ID: 50f7fa8876d6
Revises: b75ada202a8b
Create Date: 2025-06-18 19:20:17.269998

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f7fa8876d6'
down_revision: Union[str, None] = 'b75ada202a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard', sa.Column('normal_form', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standard', 'normal_form')
    # ### end Alembic commands ###
