"""completed_standard_fields

Revision ID: dd643eb05c33
Revises: 29b6e9de8f6e
Create Date: 2026-01-03 02:33:56.740741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd643eb05c33'
down_revision: Union[str, None] = '29b6e9de8f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_standard', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('completed_standard', sa.Column('user_weight', sa.Float(), nullable=True))
    op.add_column('completed_standard', sa.Column('total_norm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_standard', 'total_norm')
    op.drop_column('completed_standard', 'user_weight')
    op.drop_column('completed_standard', 'weight')
    # ### end Alembic commands ###
