"""achievements

Revision ID: 5cd33ad44be8
Revises: 271c1bade92f
Create Date: 2026-02-17 23:20:28.392416

"""

import datetime
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

from src.common.models.mixins import utcnow
from src.data.database.migrations.seed_achievements import (
    COUNT_ACHIEVEMENTS,
    META_ACHIEVEMENTS,
    STREAK_ACHIEVEMENTS,
    WEIGHT_ACHIEVEMENTS,
)
from src.data.models import Achievement

# revision identifiers, used by Alembic.
revision: str = "5cd33ad44be8"
down_revision: Union[str, None] = "271c1bade92f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievement",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "rarity",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "condition_type",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("standard_id", sa.Uuid(), nullable=True),
        sa.Column("target_value", sa.Float(), nullable=False),
        sa.Column(
            "time_period",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("parent_meta_achievement_id", sa.Uuid(), nullable=True),
        sa.Column(
            "meta_tier",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("is_meta_group", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_meta_achievement_id"],
            ["achievement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["standard_id"],
            ["standard.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_achievement_category"), "achievement", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_achievement_condition_type"),
        "achievement",
        ["condition_type"],
        unique=False,
    )
    op.create_index(op.f("ix_achievement_name"), "achievement", ["name"], unique=False)
    op.create_table(
        "user_streak",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("last_activity_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_streak_user_id"), "user_streak", ["user_id"], unique=True
    )
    op.create_table(
        "user_achievement",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("achievement_id", sa.Uuid(), nullable=False),
        sa.Column("earned_at", sa.DateTime(), nullable=False),
        sa.Column("progress_at_earned", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_achievement_achievement_id"),
        "user_achievement",
        ["achievement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_achievement_user_id"),
        "user_achievement",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_achievement_progress",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("achievement_id", sa.Uuid(), nullable=False),
        sa.Column("current_value", sa.Float(), nullable=False),
        sa.Column("is_earned", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_achievement_progress_achievement_id"),
        "user_achievement_progress",
        ["achievement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_achievement_progress_user_id"),
        "user_achievement_progress",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "credit",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )

    # Заполняем таблицу achievement начальными данными
    _populate_achievements()

    # ### end Alembic commands ###


def _populate_achievements():
    """Заполнить таблицу achievement начальными данными"""
    now = utcnow()

    def prepare_achievements(achievements, condition_type, time_period=None):
        """Подготовить ачивки для вставки"""
        result = []
        for ach in achievements:
            result.append(
                {
                    "id": ach["id"],
                    "name": ach["name"],
                    "description": ach["description"],
                    "icon": ach["icon"],
                    "rarity": ach["rarity"],
                    "condition_type": condition_type,
                    "standard_id": ach.get("standard_id"),
                    "target_value": ach["target_value"],
                    "time_period": time_period,
                    "parent_meta_achievement_id": ach.get("parent_meta_achievement_id"),
                    "meta_tier": ach.get("meta_tier"),
                    "is_meta_group": ach.get("is_meta_group", False),
                    "is_active": True,
                    "created_at": now,
                    "updated_at": now,
                }
            )
        return result

    # COUNT ачивки
    count_achievements = prepare_achievements(COUNT_ACHIEVEMENTS, "count", "total")

    # WEIGHT ачивки
    weight_achievements = prepare_achievements(WEIGHT_ACHIEVEMENTS, "weight", "total")

    # STREAK ачивки
    streak_achievements = prepare_achievements(STREAK_ACHIEVEMENTS, "streak")

    # META ачивки
    meta_achievements = prepare_achievements(META_ACHIEVEMENTS, "meta")

    # Объединяем все ачивки
    all_achievements = (
        count_achievements
        + weight_achievements
        + streak_achievements
        + meta_achievements
    )

    # Вставляем данные
    op.bulk_insert(Achievement.__table__, all_achievements)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credit",
        "completed_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_user_achievement_progress_user_id"),
        table_name="user_achievement_progress",
    )
    op.drop_index(
        op.f("ix_user_achievement_progress_achievement_id"),
        table_name="user_achievement_progress",
    )
    op.drop_table("user_achievement_progress")
    op.drop_index(op.f("ix_user_achievement_user_id"), table_name="user_achievement")
    op.drop_index(
        op.f("ix_user_achievement_achievement_id"), table_name="user_achievement"
    )
    op.drop_table("user_achievement")
    op.drop_index(op.f("ix_user_streak_user_id"), table_name="user_streak")
    op.drop_table("user_streak")
    op.drop_index(op.f("ix_achievement_name"), table_name="achievement")
    op.drop_index(op.f("ix_achievement_condition_type"), table_name="achievement")
    op.drop_index(op.f("ix_achievement_category"), table_name="achievement")
    op.drop_table("achievement")
    # ### end Alembic commands ###
